# Generated by Django 2.2.13 on 2020-09-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_headline_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
