# Generated by Django 2.2.13 on 2020-09-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='start_time',
        ),
    ]
