# Generated by Django 2.2 on 2020-02-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(verbose_name='value of x')),
                ('y', models.FloatField(verbose_name='value of y')),
                ('z', models.FloatField(verbose_name='value of z')),
            ],
        ),
    ]
